import type { Spec } from './schemas.js';

export interface SpecMeta {
  issueNumber: number;
  title: string;
  classification: string;
}

function bulletList(items: string[], emptyText = '_None._'): string {
  if (items.length === 0) return emptyText;
  return items.map((i) => `- ${i}`).join('\n');
}

/** The committed `spec.md` body — the source of truth re-read by later phases. */
export function renderSpecMarkdown(spec: Spec, meta: SpecMeta): string {
  const requirements = spec.requirements
    .map((r) => `- **${r.id}** \`[${r.confidence}]\` ${r.statement}`)
    .join('\n');

  const acceptance = spec.acceptanceCriteria
    .map(
      (ac) =>
        `### ${ac.id}\n\n- **Given** ${ac.given}\n- **When** ${ac.when}\n- **Then** ${ac.then}`,
    )
    .join('\n\n');

  return [
    `# Spec — Issue #${meta.issueNumber}: ${meta.title}`,
    '',
    `**Type:** ${meta.classification}`,
    '',
    '> Generated by Tsukinome. This file is the source of truth for the work; edits here drive the build.',
    '',
    '## Summary',
    '',
    spec.summary,
    '',
    '## Requirements',
    '',
    'Each requirement is tagged with a confidence level (explicit / inferred / assumption / unknown).',
    '',
    requirements || '_None._',
    '',
    '## Acceptance Criteria',
    '',
    acceptance || '_None._',
    '',
    '## Non-Goals',
    '',
    bulletList(spec.nonGoals),
    '',
    '## Edge Cases',
    '',
    bulletList(spec.edgeCases),
    '',
    '## Assumptions',
    '',
    bulletList(spec.assumptions),
    '',
    '## Open Questions',
    '',
    bulletList(spec.openQuestions, '_None._'),
    '',
  ].join('\n');
}

/** Shorter issue-comment summary, including the assumptions Tsukinome is making. */
export function renderSpecComment(spec: Spec): string {
  const sections = [
    "📋 **Spec drafted.** Here's my understanding — committed to `.tsukinome/` on a working branch.",
    spec.summary,
    `**Requirements:** ${spec.requirements.length} · **Acceptance criteria:** ${spec.acceptanceCriteria.length}`,
    `## Assumptions I'm making\n\n${bulletList(spec.assumptions, '_None — the issue was fully specified._')}`,
  ];
  if (spec.openQuestions.length > 0) {
    sections.push(`## Open questions\n\n${bulletList(spec.openQuestions)}`);
  }
  return sections.join('\n\n');
}
